version: '3.8'

services:
  rinna-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./lora-rinna-3.6b-optimized:/app/lora-rinna-3.6b-optimized:ro
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped